sudo: false
language: java

dist:
  - trusty

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/com/zaxxer

cache:
  directories:
    - $HOME/.m2/repository

install: /bin/true

jdk: openjdk11

script:
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --feature 11 --target $JAVA_HOME
  - mvn package --global-toolchains ./travis-toolchains.xml -Dmaven.javadoc.skip=true -V -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
